# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3b65b74a8a9cb483dc2e5a611026b04692bddbba618d29f3680294ee4b8e6f911aacb7d33e893b68c06bd811846ce7d985144dcb9318eee5ac87f6cf74d4f8

test:
  secret_key_base: 038917141385555c6351f6bd07046d6960d62995c37ae82dd416dc38c922fcc420c6c849443582dfe1ddd3224079a4a84f8c19819fd19015ef20a07aab6c488b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
